import {nativeShopUI,updateShopDaily} from './native-shop-ui.js';
import {gameSaveTransaction} from './game-save-transaction.js';
import {storageCapacityDialog} from './storage-capacity-ui.js';
import {claimAllOfflinePacks} from './offline-shop.js';
import {ticketLabel} from './offline-currency.js';
import {originalStoneIconName} from './client-stone-icon.js';
import {nativeMonsterRecycleReward,originalMonsterRecycleRewardItems} from './native-monster-recycle-reward.js';
import {nativeMonsterRecycleConfirmation} from './native-monster-recycle-confirmation.js';
import {originalAutoGamePlan} from './client-original-auto-equip.js';
import {nativeMonsterDetailUI,bindNativeMonsterDetailUI} from './native-monster-detail-ui.js';
import {originalCustomMonsterFramePlan} from './client-custommonster-frame-rules.js';
import {prepareOriginalPokemonFrame,drawOriginalPokemonFrame,clearOriginalPokemonFrame} from './native-pokemon-frame.js';
import {updateOriginalBossDeaths,originalBossDeathPending} from './native-scene.js';
import {nativeTeamUI,bindNativeTeamUI} from './native-team-ui.js';
import {drawOriginalTeamModels,prepareOriginalTeamModels} from './native-scene.js';
import {preloadOriginalActorPortraits} from './native-actor-portraits.js';
import {nativeFailureExplanation,nativeBattleConfirmation,nativeBattlePauseUI,nativeBattlePauseItems} from './native-battle-failure-ui.js';
import {nativeStageSelectUI,bindNativeStageCarousel} from './native-stage-select-ui.js';
import {nativeRegionDescription} from './native-stage-description-ui.js';
import {nativeTapMarker} from './native-tap-marker.js';
import {nativeExpeditionBonus} from './native-bonus-ui.js';
import {nativeResourceHUD,updateNativeResourceHUD} from './native-hud-ui.js';
import {nativeExperienceResult,nativeLootResult} from './native-result-ui.js';
import {nativeStarterUI,placeStarterActors,STARTER_WORLD_POINTS} from './native-starter-ui.js';
import {nativeRecruitUI} from './native-recruit-ui.js';
import {nativeCookingUI} from './native-cooking-ui.js';
import {nativeBingoLines} from './native-detail-ui.js';
import {originalSprite,paintNativeLabels} from './native-ui.js';
import {createOriginalAudio} from './client-audio.js';
import {originalPokemonVoice} from './client-pokemon-voice.js';
import {originalPokemonIconPath} from './client-pokemon-portrait-source.js';
import {renderOriginalScene,updateOriginalStarterActors,updateOriginalBattleActors,updateOriginalCampActors,updateOriginalBattleEffects,projectOriginalStarter,followOriginalBattle,placeOriginalCampGoods,projectOriginalCamp,projectOriginalBattle,getOriginalBattleLayout,prepareOriginalBattle,projectOriginalIsland,focusOriginalIsland,panOriginalIsland,panOriginalCamp,projectOriginalCampPot,ready as nativeSceneReady} from './native-scene.js';
import * as E from './engine.js';
import * as M from './meta.js';
import {icon,ingredientIcon} from './icons.js';
import {drawScene,drawMonster,drawMap} from './renderer.js';
const $=s=>document.querySelector(s),all=x=>Array.isArray(x)?x:Object.values(x||{}),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let game=new URLSearchParams(location.search).get('preview')==='1'?E.createTransientGame():E.loadGame(),view=game.starterChosen?'camp':'starter',selected=game.team[0],starter='bulbasaur',battle=null,auto=localStorage.getItem('quest-auto')==='on',speed=1,area=1,stageId='1-1',food=[],pot='normal',recipePage=0,questTab='main',shopTab='service',slot=0,trainMode='level',trainMoveIndex=0,supports=[],ended=false,sound=localStorage.getItem('quest-sound')!=='off';
let localBackupText='';
const audio=createOriginalAudio();let musicMode=null,audioUnlocked=false;
function syncMusic(){if(!audioUnlocked)return;audio.setMuted(!sound);const mode=battle?(battle.status==='won'?'victory':battle.units?.some(u=>u.isBoss&&u.hp>0)?(battle.stage.bossBgmEventID||'boss'):(battle.stage.stageBgmEventID||'battle')):view==='starter'?'title':view==='map'||view==='area'?'stageSelect':'camp';if(musicMode!==mode){musicMode=mode;audio.playMusic(mode).catch(console.error)}}
const SLOT_DISPLAY=[6,7,8,2,0,1,3,4,5];
const sp=id=>E.SPECIES.find(s=>s.id===id),mon=id=>game.monsters.find(m=>m.uid===id),mv=id=>E.MOVES.find(m=>m.id===id),foodItem=id=>E.INGREDIENTS.find(i=>i.id===id),col={red:'#eb6056',blue:'#438ed2',yellow:'#eabc31',gray:'#787c70',rainbow:'linear-gradient(135deg,#f48cb5,#f7db56,#7addd5)',shell:'#845171'};
M.initMeta(game);
function save(){M.initMeta(game);if(!battle)E.refreshDailyVisitor(game);const saved=E.saveGame(game);if(!saved)notify('本地保存失败，请先导出存档备份，再检查浏览器存储空间');return saved;}function notify(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function run(fn){try{const r=fn();if(r===false||r?.ok===false)notify(r?.message||'无法执行，请检查条件');else if(r?.message)notify(r.message);save();render();return r}catch(e){notify(e.message);console.error(e)}}
function pokemonIcon(s){const path=originalPokemonIconPath(s.dex);return path?`<img class="portrait original-pokemon-icon" src="${path}" alt="" aria-hidden="true">`:portrait(s);}
function portrait(s,extra=''){return `<canvas class="portrait ${extra}" data-species="${esc(s.id)}" data-shiny="${!!s.shiny}" width="180" height="140"></canvas>`}
let teamUIState={page:undefined,order:'level'},disposeTeamBindings=()=>{};
let detailUIState={page:0,profile:false,selectedStone:''},disposeDetailBindings=()=>{};
function paint(){disposeDetailBindings();disposeDetailBindings=bindNativeMonsterDetailUI(document.querySelector('#ui'),{onRender:state=>{detailUIState={...detailUIState,...state};render();},onAuto:autoSetDetailStones,onRecycle:showDetailRecycle,onRecycleMode:mode=>{detailUIState={...detailUIState,recycleMode:mode,recycleSelection:[],selectedStone:'',profile:false};render();},onRecycleSelection:ids=>{const attached=new Set(game.monsters.flatMap(m=>[...m.slots,...m.moveSlots.flat()]));detailUIState={...detailUIState,recycleSelection:ids.filter(id=>!attached.has(id)).slice(0,9)};render();},onRecycleConfirm:confirmDetailRecycle,onMoveStoneDrop:p=>run(()=>E.equipMoveStone(game,selected,p.stoneId,p.moveIndex,p.stoneSlot)),onMoveStoneRemove:p=>run(()=>E.removeMoveStone(game,p.originMonster,p.originMoveIndex,p.originStoneSlot)),onSort:sortState=>{detailUIState={...detailUIState,sortState,page:0};render();},onReset:()=>run(()=>{for(let i=0;i<9;i++)if(mon(selected).slots[i])E.equipStone(game,selected,null,i);return{ok:true};})});disposeTeamBindings();disposeTeamBindings=bindNativeTeamUI(document.querySelector('#ui'),{onRender:state=>{teamUIState=state;render();},onToggle:uid=>{selected=uid;run(()=>E.toggleTeam(game,uid));}});bindNativeStageCarousel(document.querySelector('.native-stage-select'));paintNativeLabels();document.querySelectorAll('[data-species]').forEach(c=>{const s=sp(c.dataset.species),draw=()=>{if(c.isConnected){const context=c.getContext('2d');context.clearRect(0,0,c.width,c.height);drawMonster(context,90,120,130,s,{time:0,shiny:c.dataset.shiny==="true"})}};draw();preloadOriginalActorPortraits([s],{shiny:c.dataset.shiny==="true"}).then(draw)});const c=$('#team-art');if(c)prepareOriginalTeamModels().catch(console.error);}
function skillIcon(id){return originalSprite('button_skill_'+mv(id)?.client?.m_iconPath,'native-skill-icon')}
function foodIcon(id){const f=foodItem(id);return f?ingredientIcon(id):''}
function gem(s){return originalSprite(originalStoneIconName(s),'native-stone-gem')}
function back(target='camp',text='↩'){return `<button class="back pink" data-view="${target}" aria-label="返回${target==='camp'?'大本营':'上一页'}">${icon('back')}</button>`}
function screen(title,body,extra=''){return `<section class="sub-screen ${extra}"><div class="sub-title">${title}</div>${body}</section>`}
function hud(title='大本营'){E.refreshEnergy(game);return `<div class="top-left"><div class="page-label"><span class="label-icon">${icon(view==='map'||view==='area'?'map':'camp')}</span>${title}</div></div>${nativeExpeditionBonus(game.expeditionBonus)}${nativeResourceHUD(game)}`}
function bottom(map=false){return `<div class="bottom-left"><button class="square-button" data-view="options">${icon('gear')}选项</button><button class="square-button" data-view="quests">${icon('quest')}任务</button><button class="square-button" data-view="dex">${icon('dex')}图鉴</button></div><div class="team-power">${originalSprite('window_power_pokemon','native-team-power-icon')}<strong>${E.teamPower(game).toLocaleString()}</strong></div><div class="camp-team"><button class="edit" data-view="team">${icon('team')}队伍编成</button>${Array.from({length:3},(_,i)=>{const m=mon(game.team[i]);return m?`<button class="mini-monster ${i===1?'green':i===2?'blue':''}" data-monster="${m.uid}">${pokemonIcon(sp(m.speciesId))}<small>${esc(sp(m.speciesId).name)}</small></button>`:`<button class="mini-monster ${i===1?'green':i===2?'blue':''}" data-view="team"><span style="font-size:35px">＋</span></button>`}).join('')}</div><button class="expedition" data-view="${map?'camp':'map'}"><i>${icon(map?'camp':'map')}</i>${map?'大本营':'出发探险'}</button>`}
function selectedInfo(m){const s=sp(m.speciesId),st=E.monsterStats(game,m);return `<div class="selected-info">${portrait(s)}<div>${esc(s.name)}<br><small>Lv.${m.level}　${s.types.join(' / ')}<br>${s.range?'远距离':'近距离'}</small></div><div class="info-stats">♥ HP ${st.hp}<br><b>▣ ATK ${st.atk}</b></div></div>`}
function tiles(mode='select'){return `<div class="monster-grid">${game.monsters.map(m=>`<button class="monster-tile ${m.uid===selected||supports.includes(m.uid)?'selected':''}" draggable="true" data-drag-monster="${m.uid}" data-${mode}="${m.uid}">${portrait({...sp(m.speciesId),shiny:m.shiny})}<small>Lv.${m.level}${game.team.includes(m.uid)?'　♟':''}</small></button>`).join('')}</div>`}
function showDialog(html){$('#overlay').hidden=false;$('#overlay').innerHTML=`<section class="dialog">${html}</section>`;paint()}
function closeDialog(){if(battle?.paused)E.pauseBattle(battle);$('#overlay').hidden=true;$('#overlay').innerHTML=''}
const mapPositions=[[220,370],[300,270],[400,150],[540,280],[365,440],[725,225],[590,425],[715,150],[775,405],[520,165],[650,495],[910,90]];
function campVisitorUI(){
 if(!game.tutorial?.worldMapDialogCompleted)return '';
 const visitor=game.dailyVisitor?.pending,remaining=Math.max(0,22*3600000-(Date.now()-(game.dailyVisitor?.clock??Date.now()))),minutes=Math.ceil(remaining/60000);
 return `<button class="camp-visitor" data-action="daily-visitor" ${visitor?'':'disabled'}>${visitor?`${pokemonIcon(sp(visitor.speciesId))}<span>来访伙伴：${esc(sp(visitor.speciesId).name)} · Lv.${visitor.level}<small>点击邀请加入</small></span>`:`<span>营地访客<small id="visitor-countdown">下次来访约 ${Math.floor(minutes/60)} 小时 ${minutes%60} 分钟</small></span>`}</button>`;
}
function render(){if(view==='camp'&&!battle)E.refreshDailyVisitor(game);placeOriginalCampGoods((game.placedDecorations||[]).map(id=>M.DECORATIONS.find(d=>d.id===id)?.sourceId).filter(id=>id!==undefined)).catch(console.error);if(!mon(selected))selected=game.team[0];let html='';const m=mon(selected);
 if(view==='starter')html=nativeStarterUI({starters:E.STARTERS,selected:starter,species:sp,portrait,project:projectOriginalStarter});
 if(view==='camp')html=hud()+`<button class="decoration" data-view="decorations">${icon('decor')}装饰</button><button class="pot-marker" data-view="cook" aria-label="打开料理锅">${game.cooking?game.cooking.ready?'✓':`<small>${game.cooking.remaining}</small>`:icon('pot')}</button><button class="pot-hotspot" data-view="cook" aria-label="料理锅"></button>${campVisitorUI()}`+bottom();
 if(view==='map'){html=hud('探险')+E.REGIONS.map((r,i)=>{const unlocked=E.isStageUnlocked(game,r.stages[0]),done=r.stages.every(s=>game.cleared.includes(s.id)),[x,y]=mapPositions[i];return `<button class="map-node ${done?'done':''} ${unlocked?'':'locked'}" style="left:${x/1000*100}%;top:${y/600*100}%" data-area="${r.id}" ${unlocked?'':'disabled'}>${unlocked?r.id:'▣'}<small>${esc(r.name)}</small></button>`}).join('')+bottom(true)}
 if(view==='area'){const r=E.REGIONS.find(r=>r.id===area);html=hud('探险')+`<div class="area-backdrop"></div>${nativeRegionDescription(r)}${nativeStageSelectUI({region:r,game,stageUnlocked:E.isStageUnlocked,teamPower:E.teamPower})}<div class="area-team">${bottom(true)}</div>${back('map')}`}

 if(view==='team')html=nativeTeamUI({game,selected,species:sp,teamPower:E.teamPower,monsterStats:E.monsterStats,expProgress:m=>m.level>=100?1:m.xp/E.nextLevelXp(m.level),...teamUIState});
 if(view==='cook'){
  const p=E.POTS.find(p=>p.id===(game.cooking?.potId||pot))||E.POTS[0],r=E.RECIPES[recipePage],shownFood=game.cooking?.ingredients||food;
  html=nativeCookingUI({pot:p,ingredients:E.INGREDIENTS,food:shownFood,inventory:game.inventory,recipe:r,recipePage,description:recipeDescription(r),cooking:game.cooking,foodIcon})+`<div class="cooking-stations">${Array.from({length:E.cookingStationCount(game)},(_,i)=>{const c=E.cookingAtStation(game,i);return `<button data-cook-station="${i}" ${i===(game.activeCookingStation||0)?'class="green"':''}>料理锅 ${i+1} · ${c?c.ready?'可领取':`剩余 ${c.remaining} 次`:'空闲'}</button>`;}).join('')}</div>`;
 }
 if(view==='stones'){html=nativeMonsterDetailUI({game,monster:{...m,skillSlotIndices:m.skillSlotIndices??m.clientUniqueSkillSlots?.filter(v=>v>=0)},species:E.SPECIES,monsterStats:E.monsterStats,expProgress:m=>m.level>=100?1:m.xp/E.nextLevelXp(m.level),selectedSlot:slot,stoneIcon:gem,isSlotUnlocked:E.isSlotUnlocked,slotUnlockLevel:E.slotUnlockLevel,moveName:id=>mv(id)?.name||id,moveIcon:skillIcon,moveStoneIcon:s=>originalSprite('UI_Pstone_skill_'+({whack:'continue',broad:'extend',scatter:'nway',sharing:'addteambuff',stay:'buffprobup',wait:'charge'}[s.kind])),moveStoneName:s=>E.MOVE_STONES.find(v=>v.kind===s.kind)?.name||s.kind,moveStoneProperties:s=>[{label:E.MOVE_STONES.find(v=>v.kind===s.kind)?.description||''}],stoneBonusLabel:id=>E.STONE_BONUSES.find(v=>v.id===id)?.name||id,bingoLabel:E.bingoLabel,...detailUIState,recycleMaxCount:9});}
 if(view==='train'&&!m.moves[trainMoveIndex])trainMoveIndex=0;
 if(view==='train')html=screen('♟ 特训',`<div class="split"><div class="left-pane">${selectedInfo(m)}<div class="training-modes"><button class="${trainMode==='level'?'green':''}" data-train-mode="level">升级特训</button><button class="${trainMode==='move'?'pink':''}" data-train-mode="move">招式特训</button></div>${trainMode==='move'?`<div class="training-move-options" role="group" aria-label="选择要更换的招式">${m.moves.map((id,i)=>`<button data-train-move-index="${i}" aria-pressed="${i===trainMoveIndex}" class="${i===trainMoveIndex?'pink':''}">招式 ${i+1}：${esc(mv(id)?.name||id)}</button>`).join('')}</div>`:''}<div class="helper">选择最多 4 只支持伙伴。<br>支持伙伴在特训后会离开。</div><div class="support-grid">${Array.from({length:4},(_,i)=>{const sm=mon(supports[i]);return `<button class="support-slot" data-support-remove="${i}">${sm?portrait({...sp(sm.speciesId),shiny:sm.shiny})+`Lv.${sm.level}`:'＋'}</button>`}).join('')}</div><button class="cook-action" data-action="train" ${supports.length?'':'disabled'}>特训开始</button><button style="margin-top:25px" data-action="everstone">不变石 ${m.everstone?'ON':'OFF'}</button></div><div class="right-pane"><div class="helper">支持伙伴需先从探险队伍移出。<br>${trainMode==='move'?'招式可能改变，支持伙伴将消耗。':'伙伴获得经验，达到等级后进化。'}</div>${tiles('support')}</div></div>${back('team')}`);
 if(view==='dex')html=screen('▱ 宝可梦图鉴',`<div class="dex-grid">${E.SPECIES.map(s=>{const found=game.monsters.some(m=>m.speciesId===s.id)||game.discovered.includes(s.id);return `<button class="dex-tile ${found?'':'missing'}" data-dex="${s.id}">${portrait(s)}No.${String(s.dex).padStart(3,'0')}<br>${found?s.name:'？？？'}</button>`}).join('')}</div>${back()}`);
 if(view==='quests')html=renderQuests();if(view==='shop'||view==='decorations')html=renderShop();
 if(view==='options')html=screen('⚙ 选项',`<div class="menu-panel"><h2>选项</h2><div class="menu-grid"><button data-action="sound">声音 ${sound?'ON':'OFF'}</button><button data-action="help">帮助</button><button data-view="recipes">料理图鉴</button><button data-action="export">导出存档</button><button data-action="import">导入存档</button><button data-action="fullscreen">全屏</button></div></div>${back()}`);
 if(view==='recipes')html=screen('♨ 料理图鉴',`<div class="recipe-grid">${E.RECIPES.map((r,i)=>`<div class="recipe-card"><h3>${i+1}. ${r.name}</h3><p>${recipeDescription(r)}</p><p>偏好：${r.id==='mulligan'?'任何宝可梦':r.type||'依食材颜色而不同'}</p></div>`).join('')}</div>${back('options')}`);
 if(view==='battle')html=battleUI();$('#ui').innerHTML=html;paint();syncMusic();
}
function restoreBackupText(text){const restored=E.restoreGameBackup(text,game);M.initMeta(restored);game=restored;selected=game.team[0];view='camp';closeDialog();save();render();notify('存档导入完成')}
function downloadBackup(){const blob=new Blob([localBackupText],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='pokemon-quest-save.json';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);}
function recipeDescription(r){const ruleNames={red:'红色',blue:'蓝色',yellow:'黄色',gray:'灰色',soft:'柔软',hard:'坚硬',mushroom:'蘑菇',sweet:'甜',mineral:'矿物',plant:'植物',shell:'神秘贝壳'};return Object.entries(r.rules).map(([k,v])=>`${ruleNames[k]||k}食材 ${v} 格以上`).join('，')||'任何五格食材。'}
function battleUI(){return `<div class="native-battle-hud"><div class="battle-top"><button class="pause" data-action="pause" aria-label="暂停">${originalSprite('button_allround_pose','native-battle-pause-icon')}</button><span class="drop-counter native-stones" aria-label="获得方石"><span class="native-battle-drop-frame"></span>${originalSprite('drop_icon_stone','native-battle-drop-icon')}<span class="native-battle-drop-divider"></span><span class="native-drop-value" id="battle-stones">0</span></span><span class="drop-counter native-food" aria-label="获得食材"><span class="native-battle-drop-frame"></span>${originalSprite('drop_icon_kinomi','native-battle-drop-icon')}<span class="native-battle-drop-divider"></span><span class="native-drop-value" id="battle-food">0</span></span></div><div class="waves" aria-label="探险波次">${Array.from({length:battle.maxWaves},(_,i)=>`<span id="wave-${i}" class="${i<battle.wave?'lit':''}"></span>`).join('')}</div>${battle.timeLimit>0?`<div class="timer" id="timer">${Math.ceil(battle.timeLimit)}</div>`:''}<button class="auto" data-action="auto" aria-label="自动战斗 ${auto?'开启':'关闭'}">${originalSprite('window_button_commonUI','native-auto-frame')}${originalSprite(auto?'button_battle_auto':'button_battle_manual','native-auto-icon')}<span class="native-auto-label">AUTO</span></button><button class="scatter" id="scatter" data-action="scatter" aria-label="散开">${originalSprite('window_button_commonUI','native-scatter-frame')}${originalSprite('button_battle_runaway','native-scatter-icon')}</button><div class="battle-bottom">${game.team.map((uid,i)=>{const u=battle.units.find(u=>u.uid===uid),m={...mon(uid),moves:u?.moves||mon(uid).moves};return `<div class="skill-card" data-team-index="${i}" style="--team-index:${i}"><span class="native-battle-shell"></span><span class="native-battle-inner"></span><span class="native-battle-portrait-frame"></span><div class="native-battle-portrait">${pokemonIcon(sp(m.speciesId))}<span class="name">${sp(m.speciesId).name}</span></div><span class="native-battle-hp-frame"></span><div class="hpbar" aria-label="${esc(sp(m.speciesId).name)} 体力"><div id="hp-${i}" style="width:100%"></div></div><div class="move-buttons">${m.moves.map((id,j)=>`<button class="move-button" data-move-index="${j}" data-skill="${i}|${j}" aria-label="${esc(mv(id)?.name||id)}">${skillIcon(id)}<span class="native-move-name">${esc(mv(id)?.name||id)}</span><div class="cooldown-cover" id="cooldown-${i}-${j}" style="display:none"></div></button>`).join('')}${m.moves.length===1?'<span class="move-button native-empty-move" aria-hidden="true"></span>':''}</div></div>`}).join('')}</div></div>`}
function renderQuests(){const QUESTS=M.QUESTS.filter((q,i)=>!q.unverified&&!q.unavailable&&M.questOpened(game,q)&&(q.category||(i>=21?'challenge':'main'))===questTab);return screen('▦ 任务',`<div class="quest-tabs"><button data-quest-tab="main" class="${questTab==='main'?'green':''}">主线任务</button><button data-quest-tab="challenge" class="${questTab==='challenge'?'green':''}">挑战任务</button></div><div class="quest-list">${QUESTS.map(q=>{const n=Math.min(M.questProgress(game,q),q.goal),claimed=(game.questRewards.includes(q.id)||q.aliases?.some(id=>game.questRewards.includes(id)));return `<div class="quest-row"><div>${q.name}<small>${q.description}<br>${n} / ${q.goal}　${M.questRewardLabel(q.reward)}</small><div class="task-progress"><div style="width:${n/q.goal*100}%"></div></div></div><button data-quest="${q.id}" ${n<q.goal||claimed?'disabled':''}>${claimed?'已领取':'领取'}</button></div>`}).join('')}</div>${back()}`)}
function renderShop(){return nativeShopUI({game,tab:view==='decorations'?'goods':shopTab,decorations:M.DECORATIONS,tickets:ticketLabel(game),sprite:originalSprite})}
function beep(){if(sound)audio.playEffect('click').catch(console.error)}
function go(v){if(battle&&v!=='battle')return;if(v==='map'&&game.tutorial?.recruited&&!game.tutorial.worldMapDialogCompleted)E.completeWorldMapTutorial(game);if(v==='map'&&view!=='area')focusOriginalIsland(area);if(view==='stones'&&v!=='stones')clearOriginalPokemonFrame();if(v==='stones'&&view!=='stones'){detailUIState={page:0,profile:false,selectedStone:''};slot=0;}view=v;render()}
function begin(){if(game.tutorial.completed&&game.stones.length+game.moveStones.length>=game.boxCapacity.stones){showDialog(storageCapacityDialog(game,'stones'));return}run(()=>{if(!game.tutorial.completed)stageId='tutorial';battle=E.startBattle(game,stageId);const loadingBattle=battle;loadingBattle.loading=true;prepareOriginalBattle({...battle.stage,clientMapId:battle.clientStage?.m_mapDataID,clientDungeonId:battle.clientStage?.m_dungeonID,clientChallengeStage:battle.clientStage?.m_stageNo,clientPrevLocalID:battle.clientStage?.m_localID,clientEnemyPackName:battle.clientStage?.enemyPackName,actorSpecies:[...battle.units.filter(u=>!u.isEnemy).map(u=>sp(u.speciesId).dex),...battle.phases.flat().map(row=>row.dex||sp(row.speciesId)?.dex)].filter(Boolean)}).then(ready=>{if(ready&&battle===loadingBattle)E.configureBattleWorld(battle,getOriginalBattleLayout());}).catch(console.error).finally(()=>{loadingBattle.loading=false});view='battle';ended=false;lastReward=null;failureDialogAt=null;render()})}
function cookingResult(){const knownSpecies=new Set(game.discovered);const r=run(()=>E.claimCooking(game));if(r?.ok===false&&(r.reason==='monster-storage-full'||r.message?.includes('伙伴盒空间不足'))){showDialog(storageCapacityDialog(game,'monsters',r.required));return}if(r?.ok){const recruits=r.monsters||[r.monster],isNew=recruits.some(m=>!knownSpecies.has(m.speciesId));for(const m of recruits)game.discovered.push(m.speciesId);selected=r.monster?.uid||selected;view='camp';render();if(!recruits.length){notify('料理完成，这次没有伙伴来访');save();return}showDialog(nativeRecruitUI({names:recruits.map(m=>sp(m.speciesId).name),monsterCount:game.monsters.length,capacity:game.boxCapacity.monsters,isNew}));save()}}

function doTrain(){if(!supports.length)return;showDialog(`<h2>开始${trainMode==='level'?'升级':'招式'}特训？</h2><p>${trainMode==='move'?`将更换招式 ${trainMoveIndex+1}：${esc(mv(mon(selected).moves[trainMoveIndex])?.name||mon(selected).moves[trainMoveIndex])}。<br>`:''}这 ${supports.length} 只支持宝可梦会在特训后离开。已装备方石会保留在库存中。</p><div class="dialog-actions"><button class="pink" data-action="close">取消</button><button data-action="confirm-train">开始特训</button></div>`)}
document.addEventListener('native-stage-selected',e=>{if(e.detail?.stageId)stageId=e.detail.stageId});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(!audioUnlocked){audioUnlocked=true;audio.unlock().then(syncMusic).catch(console.error)}beep();const d=b.dataset;
 if(d.shopTab){shopTab=d.shopTab;view='shop';render()}if(d.view)go(d.view);if(d.starter){starter=d.starter;render()}if(d.select&&selected!==d.select){selected=d.select;render()}if(d.monster){selected=d.monster;go('stones')}if(d.area){area=+d.area;stageId=E.REGIONS[area-1].stages[0].id;view='area';render()}if(d.stage){stageId=d.stage;render()}if(d.previewStage){stageId=d.previewStage;begin()}
 if(d.cookStation!==undefined){const r=run(()=>E.selectCookingStation(game,+d.cookStation));if(r?.ok){food=[];render();}}if(d.expandBox){run(()=>E.expandBox(game,d.expandBox))}if(d.questTab){questTab=d.questTab;render()}if(d.food){if(game.cooking)return;if(food.length>=5)return notify('五格食材已放满');const p=E.POTS.find(p=>p.id===pot),needed=(food.filter(id=>id===d.food).length+1)*p.cost;if(needed>game.inventory[d.food])return notify('食材不足');food.push(d.food);render()}if(d.removeFood!==undefined&&!game.cooking){food.splice(+d.removeFood,1);render()}if(d.recipe){recipePage=(recipePage+ +d.recipe+E.RECIPES.length)%E.RECIPES.length;render()}
 if(d.slot!==undefined){slot=+d.slot;render()}if(d.stone)run(()=>E.equipStone(game,selected,d.stone,slot));if(d.moveEquip!==undefined){const i=+d.moveEquip;showDialog(`<h2>招式石</h2><p>${mv(mon(selected).moves[i])?.name}：选择招式石装备。</p>${game.moveStones.map(s=>{const def=E.MOVE_STONES.find(v=>v.kind===s.kind);return `<button style="margin:8px" data-equip-move="${s.id}|${i}">${def?.name||s.kind}</button>`}).join('')||'<p>探险后可能获得招式石。</p>'}<div class="dialog-actions"><button data-action="close">返回</button></div>`)}if(d.equipMove){const[id,i]=d.equipMove.split('|');run(()=>E.equipMoveStone(game,selected,id,+i));closeDialog()}
 if(d.trainMoveIndex!==undefined){const index=Number(d.trainMoveIndex);if(Number.isInteger(index)&&index>=0&&index<mon(selected).moves.length){trainMoveIndex=index;render();}}if(d.trainMode){trainMode=d.trainMode;supports=[];render()}if(d.support){if(d.support===selected||game.team.includes(d.support))return notify('目标和探险队成员不能作为支持伙伴');if(supports.includes(d.support))supports=supports.filter(id=>id!==d.support);else if(supports.length<4)supports.push(d.support);else return notify('最多 4 只支持伙伴');render()}if(d.supportRemove!==undefined){supports.splice(+d.supportRemove,1);render()}
 if(d.skill&&battle){const[i,j]=d.skill.split('|').map(Number);E.requestSkill(game,battle,i,j)}if(d.dex){const s=sp(d.dex),found=game.monsters.some(m=>m.speciesId===s.id)||game.discovered.includes(s.id);if(found)showDialog(`<h2>No.${s.dex} ${s.name}</h2><div style="width:180px;margin:auto">${portrait(s)}</div><p style="text-align:center">${s.types.join(' / ')}　${s.range?'远距离':'近距离'}<br>基础 HP ${s.hp}　基础 ATK ${s.atk}</p><div class="dialog-actions"><button data-action="close">返回</button></div>`)}
 if(d.quest)run(()=>M.claimQuest(game,d.quest));
 if(d.buy)run(()=>M.purchaseDecoration(game,d.buy));
 if(d.place)run(()=>gameSaveTransaction(game,E.saveGame,()=>{if(!game.decorations.includes(d.place))return false;if(game.placedDecorations.includes(d.place))game.placedDecorations=game.placedDecorations.filter(id=>id!==d.place);else game.placedDecorations.push(d.place);return{ok:true,message:'装饰已更新'}}));
 const a=d.action;if(!a)return;
 if(a==='choose-starter'){const r=run(()=>E.chooseStarter(game,starter));if(r?.ok){selected=game.team[0];game.discovered.push(starter);view='camp';save();render();showDialog('<h2>开始探险吧！</h2><p>和第一位伙伴一起踏上方可乐岛。伙伴自动移动和攻击，点击下方招式按钮发动招式。</p><div class="dialog-actions"><button data-action="start-tutorial">出发！</button></div>')}}
 if(a==='offline-all-packs')run(()=>claimAllOfflinePacks(game));if(a==='close')closeDialog();if(a==='toggle-team')run(()=>E.toggleTeam(game,selected));if(a==='begin'){closeDialog();begin()}if(a==='start-tutorial'){closeDialog();stageId='tutorial';begin()}if(a==='cook'){const r=run(()=>E.cook(game,food,pot));if(r?.ok){food=[];view='camp';save();render()}}if(a==='claim-cook')cookingResult();
 if(a==='change-pot')showDialog(`<h2>选择料理锅</h2><div class="pot-selection">${E.POTS.map(p=>`<button data-pot="${p.id}" ${p.unlock&&!game.cleared.includes(p.unlock)&&!(game.unlockedPots||[]).includes(p.id)?'disabled':''}>${p.name}<br>每格 ${p.cost}<br>Lv.${p.minLevel}–${p.maxLevel}</button>`).join('')}</div><div class="dialog-actions"><button data-action="close">返回</button></div>`);
 if(a==='autofill'&&game.tutorial.phase==='cook'&&!game.tutorial.recruited){food=[...E.TUTORIAL_COOK_INGREDIENTS];render()}else if(a==='autofill'){food=[];const p=E.POTS.find(p=>p.id===pot),inv={...game.inventory};for(let i=0;i<5;i++){const f=E.INGREDIENTS.find(f=>inv[f.id]>=p.cost);if(!f)break;food.push(f.id);inv[f.id]-=p.cost}render()}
 if(a==='unequip')run(()=>E.equipStone(game,selected,null,slot));if(a==='auto-stones')autoSetDetailStones();
 if(a==='storage-organize'){closeDialog();if(d.storageKind==='stones'){view='stones';selected=mon(selected)?selected:game.monsters[0]?.uid;showDetailRecycle();}else{view='train';trainMode='level';supports=[];selected=mon(selected)?selected:game.monsters[0]?.uid;render();}}
 if(a==='storage-expand'){closeDialog();view='shop';shopTab='case';render();}
 if(a==='recycle')showDetailRecycle();
 if(a==='train')doTrain();if(a==='confirm-train'){closeDialog();const r=run(()=>E.train(game,selected,supports,trainMode,trainMoveIndex));if(r?.ok||r?.consumed)supports=[];render()}if(a==='everstone')run(()=>gameSaveTransaction(game,E.saveGame,()=>{mon(selected).everstone=!mon(selected).everstone;return{ok:true,message:mon(selected).everstone?'停止进化':'允许进化'}}));
 if(a==='auto'){auto=!auto;try{localStorage.setItem('quest-auto',auto?'on':'off')}catch{}render()}if(a==='scatter'&&battle)E.scatter(battle);if(a==='pause'&&battle?.status==='fighting'){battle.paused=true;showBattlePause()}if(a==='failure-close')showBattlePause();if(a==='failure-resume'&&battle?.status==='fighting')closeDialog();if(a==='failure-forgo')showBattleDecision(false);if(a==='failure-collect'&&canRecoverBattle())showBattleDecision(true);if(a==='failure-cancel')showBattlePause();if(a==='failure-forgo-yes')finishBattleDecision(false);if(a==='failure-collect-yes'&&canRecoverBattle())finishBattleDecision(true);
 if(a==='result-experience')showExperienceResult();if(a==='result-next')showLootResult();if(a==='return-camp')returnToCamp();if(a==='daily')run(()=>{const r=E.claimDailyTickets(game);return r});if(a==='battery')showDialog('<h2>补充电池</h2><p>电池每 30 分钟回复一格。也可以消耗 25 张礼券补满。</p><div class="dialog-actions"><button class="pink" data-action="close">返回</button><button data-action="refill">补充　◈ 25</button></div>');if(a==='refill'){run(()=>E.refillBattery(game));closeDialog()}
 if(a==='daily-visitor'){const visitor=game.dailyVisitor?.pending,isNew=visitor&&!game.discovered.includes(visitor.speciesId);const r=run(()=>E.collectDailyVisitor(game));if(r?.reason==='monster-storage-full')showDialog(storageCapacityDialog(game,'monsters',1,'visitor'));else if(r?.ok){selected=r.monster.uid;render();showDialog(nativeRecruitUI({names:[sp(r.monster.speciesId).name],monsterCount:game.monsters.length,capacity:game.boxCapacity.monsters,isNew}));}}
 if(a==='retry-battle-save'&&battle)settleBattleResult(!!battle.pendingCollectDecision);if(a==='sound'){sound=!sound;localStorage.setItem('quest-sound',sound?'on':'off');syncMusic();render()}if(a==='fullscreen')$('#viewport').requestFullscreen?.();if(a==='export'){const backupGame=JSON.parse(JSON.stringify(game));M.recordLocalBackup(backupGame);localBackupText=JSON.stringify(backupGame,null,2);downloadBackup();M.recordLocalBackup(game);save();showDialog(`<h2>本地存档备份</h2><p>包含伙伴、装备和游戏进度。若下载未开始，可以复制下方文本保存。</p><textarea class="backup-text" aria-label="导出的存档文本" readonly>${esc(localBackupText)}</textarea><div class="dialog-actions"><button data-action="backup-download">下载 JSON</button><button data-action="backup-copy">复制存档文本</button><button data-action="close">返回</button></div>`);}if(a==='backup-download')downloadBackup();if(a==='backup-copy'){if(navigator.clipboard?.writeText)navigator.clipboard.writeText(localBackupText).then(()=>notify('存档文本已复制')).catch(()=>notify('请选中存档文本，使用复制快捷键保存'));else notify('请选中存档文本，使用复制快捷键保存');}if(a==='import')showDialog(`<h2>恢复本地存档</h2><p>选择 JSON 文件，或粘贴之前导出的完整存档文本。恢复成功后会替换当前进度。</p><textarea class="backup-text" aria-label="待恢复的存档文本" placeholder="粘贴完整 JSON 存档"></textarea><div class="dialog-actions"><button data-action="import-file">选择 JSON 文件</button><button data-action="import-text">恢复文本存档</button><button data-action="close">取消</button></div>`);if(a==='import-text'){try{restoreBackupText($('#overlay textarea').value)}catch(err){notify(err.message)}}if(a==='import-file'){const inp=document.createElement('input');inp.type='file';inp.accept='.json';inp.hidden=true;document.body.append(inp);inp.onchange=async()=>{try{if(inp.files?.length)restoreBackupText(await inp.files[0].text())}catch(err){notify(err.message)}finally{inp.remove()}};inp.oncancel=()=>inp.remove();inp.click()}
 if(a==='help')showDialog('<h2>探险手册</h2><p>三只伙伴自动探索。手动点击招式，或开启 AUTO。右侧散开按钮让伙伴撤开，空格也可使用。</p><p>料理需要五格食材。探险推进料理，完成后点击领取。高品质锅具消耗更多食材，吸引更高等级的伙伴。</p><p>队伍编成里进入 P 力石坠，多格方石强化 HP / ATK。特训使用支持伙伴，支持伙伴会离开。等级达到进化条件后，伙伴会进化。</p><div class="dialog-actions"><button data-action="close">返回</button></div>');
});
document.addEventListener('native-stage-selected',e=>{if(e.detail?.stageId)stageId=e.detail.stageId});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.pot){pot=b.dataset.pot;food=[];closeDialog();render()}});
document.addEventListener('keydown',e=>{if(!battle||!$('#overlay').hidden)return;if(['1','2','3'].includes(e.key))E.requestSkill(game,battle,+e.key-1,0);if(e.code==='Space'){e.preventDefault();E.scatter(battle)}if(e.key==='Escape'&&battle.status==='fighting'){battle.paused=true;showBattlePause()}});
function resize(){$('#game').style.transform=`scale(${Math.min(innerWidth/1280,innerHeight/720)})`}addEventListener('resize',resize);resize();
nativeSceneReady.then(()=>{if(view==='map')focusOriginalIsland(area)}).catch(console.error);const originalCanvas=$('#original-scene');const canvas=$('#scene'),ctx=canvas.getContext('2d');let prev=performance.now(),clock=0,uiClock=0,hudClock=0;let lastReward=null,failureDialogAt=null;
function frame(now){const dt=Math.min((now-prev)/1000,.05);prev=now;clock+=dt;syncMusic();uiClock+=dt;hudClock+=dt;if(hudClock>1){hudClock=0;if(view==='shop'&&shopTab==='service'&&updateShopDaily(game))render();const visitor=battle?{ok:false,reason:'battle'}:E.refreshDailyVisitor(game);if(visitor.generated&&view==='camp')render();const countdown=$('#visitor-countdown');if(countdown&&visitor.reason==='waiting'){const minutes=Math.ceil(visitor.remaining/60000);countdown.textContent=`下次来访约 ${Math.floor(minutes/60)} 小时 ${minutes%60} 分钟`;}E.refreshEnergy(game);updateNativeResourceHUD(game);const e=$('#energy');if(e&&e.textContent!==String(game.battery.value)){e.textContent=game.battery.value;paintNativeLabels(e.parentNode);}const c=$('#ticket-count');if(c&&c.textContent!==ticketLabel(game)){c.textContent=ticketLabel(game);paintNativeLabels(c.parentNode);}}if(battle&&!battle.loading)updateOriginalBossDeaths(battle,clock);if(battle){for(const e of battle.nativeBossDeathVoiceEvents?.splice(0)||[]){const voice=originalPokemonVoice(e.dex,e.type);if(audioUnlocked&&sound&&voice)audio.playEffect(voice.eventId).catch(console.error);}for(const e of battle.audioEvents?.splice(0)||[])if(audioUnlocked&&sound)audio.playEffect(e.eventId).catch(console.error);}if(battle&&battle.status==='fighting'&&!battle.loading&&!battle.nativeBossDeathTimeStopped){battle.auto=auto;E.tickBattle(game,battle,dt);if(uiClock>.08){uiClock=0;game.team.forEach((uid,i)=>{const u=battle.units.find(u=>u.uid===uid),hp=$(`#hp-${i}`);if(hp)hp.style.width=`${u.hp/u.maxHp*100}%`;u.moves.forEach((_,j)=>{const el=$(`#cooldown-${i}-${j}`);if(el){const state=E.battleSkillState(battle,i,j);el.style.display=state.label?'flex':'none';el.textContent=state.label;const button=el.closest('button');button.disabled=!state.enabled;button.setAttribute('aria-disabled',String(!state.enabled));}})});$('#battle-food').textContent=Object.values(battle.drops.ingredients).reduce((n,v)=>n+v,0);$('#battle-stones').textContent=battle.drops.stones.length+battle.drops.moveStones.length;if($('#timer'))$('#timer').textContent=`${Math.max(0,Math.ceil(battle.timeLimit-battle.elapsed))} s`;$('#scatter').disabled=battle.scatterCooldown>0;for(let i=0;i<battle.maxWaves;i++)$(`#wave-${i}`)?.classList.toggle('lit',i<battle.wave)}}
 if(view==='team'){const teamCanvas=$('#team-art');if(teamCanvas)drawOriginalTeamModels(teamCanvas,game,clock,E.SPECIES,E.monsterStats);}
 if(view==='stones'){const m=mon(selected),plan={...originalCustomMonsterFramePlan(sp(m.speciesId).dex,{shiny:m.shiny}),time:clock,instanceKey:m.uid};prepareOriginalPokemonFrame(plan);const canvas=$('#pokemon-detail-art');if(canvas)drawOriginalPokemonFrame(canvas,plan);} dragSurface.classList.toggle('scene-pannable',['camp','map'].includes(view));if(view==='camp'){const p=projectOriginalCampPot();if(p){const marker=$('.pot-marker'),hotspot=$('.pot-hotspot');marker.style.left=(p.x-33.5)+'px';marker.style.top=(p.y-150)+'px';hotspot.style.left=(p.x-60)+'px';hotspot.style.top=(p.y-80)+'px';marker.hidden=hotspot.hidden=!p.visible;}}if(view==='map')document.querySelectorAll('[data-area]').forEach(el=>{const p=projectOriginalIsland(+el.dataset.area);if(p){el.style.left=p.x+'px';el.style.top=p.y+'px';el.hidden=!p.visible}});if(view==='starter'){placeStarterActors(projectOriginalStarter);const rendered=updateOriginalStarterActors(clock,E.SPECIES,E.STARTERS,starter,STARTER_WORLD_POINTS)||[];document.querySelectorAll('[data-starter] .portrait').forEach(c=>c.style.visibility=rendered.includes(c.closest('[data-starter]').dataset.starter)?'hidden':'visible');}if(battle){updateOriginalBattleActors(battle,clock,E.SPECIES);followOriginalBattle(battle);updateOriginalBattleEffects(battle);}else if(view==='camp')updateOriginalCampActors(game.dailyVisitor?.pending?{...game,monsters:[...game.monsters,game.dailyVisitor.pending]}:game,clock,E.SPECIES,E.monsterStats);const nativeGround=renderOriginalScene(originalCanvas,battle?'battle':view==='starter'?'intro':view==='map'||view==='area'?'island':'camp',clock);originalCanvas.hidden=!nativeGround;if(view==='starter'){ctx.clearRect(0,0,1280,720)}else if(view==='map'||view==='area'){if(nativeGround)ctx.clearRect(0,0,1280,720);else drawMap(ctx,1280,720,{time:clock,game})}else drawScene(ctx,1280,720,{mode:battle?'battle':'camp',game,battle,time:clock,species:E.SPECIES,region:battle?.stage?.region,nativeGround,project:projectOriginalCamp,battleProject:projectOriginalBattle});
 if(battle&&battle.status!=='fighting'&&!ended&&!originalBossDeathPending(battle)){ended=true;const foodCount=$('#battle-food'),stoneCount=$('#battle-stones');if(foodCount)foodCount.textContent=Object.values(battle.drops.ingredients).reduce((n,v)=>n+v,0);if(stoneCount)stoneCount.textContent=battle.drops.stones.length+battle.drops.moveStones.length;if(battle.status==='won')settleBattleResult(false);else if(battle.status==='retreated')settleBattleResult(!!battle.collectFailedDrops);else failureDialogAt=clock+2;}if(failureDialogAt!==null&&clock>=failureDialogAt&&battle){failureDialogAt=null;$('#overlay').hidden=false;$('#overlay').innerHTML=nativeFailureExplanation({timeUp:battle.failureReason==='time'});paint()}requestAnimationFrame(frame)}
save();render();if(game.lastInterruptedExpedition&&!game.lastInterruptedExpedition.noticeShown){game.lastInterruptedExpedition.noticeShown=true;save();showDialog(`<h2>探险已中断</h2><p>已返回大本营。进入探险时使用的电池已保留消耗，本次未结算的奖励、经验和料理进度未提交。可以重新出发。</p><div class="dialog-actions"><button data-action="close">知道了</button></div>`);}requestAnimationFrame(frame);

function typeName(type){return {Fighting:'格斗',Fire:'火',Grass:'草',Flying:'飞行',Water:'水',Bug:'虫',Rock:'岩石',Ground:'地面',Psychic:'超能力',Electric:'电',Ice:'冰',Normal:'一般'}[type]||type||'无'}
// A settled expedition must leave camp without a modal input blocker.
// Tutorial reminders remain visible, but never intercept camp controls.
function returnToCamp(){
 closeDialog();
 battle=null;ended=false;lastReward=null;failureDialogAt=null;
 view='camp';render();
 const tutorial=game.tutorial;
 if(tutorial?.phase==='stone'&&!tutorial.campStoneReminderShown){
  tutorial.campStoneReminderShown=true;
  notify('点击队伍伙伴装备 P 力石，提升战力后继续探险');save();
 }
 if(tutorial?.phase==='cook'&&!game.cooking&&!tutorial.campCookingReminderShown){
  tutorial.campCookingReminderShown=true;
  notify('点击料理锅制作料理，吸引新伙伴来到营地');save();
 }
}
function showExperienceResult(){$('#overlay').hidden=false;$('#overlay').innerHTML=nativeExperienceResult({game,battle,reward:lastReward,species:sp,portrait,monsterStats:E.monsterStats,nextLevelXp:E.nextLevelXp,isSlotUnlocked:E.isSlotUnlocked,slotOrder:SLOT_DISPLAY,gem,skillIcon,moves:mv,skillCells:m=>m.clientUniqueSkillSlots?m.moves.map((moveId,i)=>({index:m.clientUniqueSkillSlots[i],moveId,label:mv(moveId)?.name})):[],teamPower:E.teamPower(game),regionName:E.REGIONS.find(r=>r.id===battle.stage.region)?.name||battle.stage.name});paint()}

function showLootResult(){$('#overlay').innerHTML=nativeLootResult({game,battle,reward:lastReward||{},ingredients:E.INGREDIENTS,foodIcon,gem,stoneBonuses:E.STONE_BONUSES,moveStones:E.MOVE_STONES,moveStoneIcon:s=>originalSprite('UI_Pstone_skill_'+({whack:'continue',broad:'extend',scatter:'nway',sharing:'addteambuff',stay:'buffprobup',wait:'charge'}[s.kind])),regionName:E.REGIONS.find(r=>r.id===battle.stage.region)?.name||battle.stage.name});paint()}

function showStageClear(){if(!lastReward?.won){showExperienceResult();return}$('#overlay').hidden=false;$('#overlay').innerHTML=`<section class="stage-clear"><div>STAGE CLEAR</div><button class="native-stage-clear-continue" data-action="result-experience" aria-label="查看探险结果">${nativeTapMarker()}</button></section>`}

let dragged=null;document.addEventListener('dragstart',e=>{const t=e.target.closest('[draggable="true"]');if(!t)return;dragged=t.dataset.dragMonster?{kind:'monster',id:t.dataset.dragMonster}:t.dataset.dragStone?{kind:'stone',id:t.dataset.dragStone,originSlot:t.dataset.stoneOriginSlot,originMonster:t.dataset.stoneOriginMonster}:t.dataset.dragFood?{kind:'food',id:t.dataset.dragFood}:null;if(dragged){e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',JSON.stringify(dragged))}});const acceptDrag=e=>{if(dragged&&e.target.closest('[data-team-slot],[data-team-remove-target],[data-stone-target],[data-stone-remove-target],[data-food-target]')){e.preventDefault();if(e.dataTransfer)e.dataTransfer.dropEffect='move';}};document.addEventListener('dragenter',acceptDrag);document.addEventListener('dragover',acceptDrag);document.addEventListener('drop',e=>{if(!dragged)return;const t=e.target.closest('[data-team-slot],[data-team-remove-target],[data-stone-target],[data-stone-remove-target],[data-food-target]');if(!t)return;e.preventDefault();const item=dragged;dragged=null;if(item.kind==='stone'&&t.dataset.stoneTarget!==undefined){slot=+t.dataset.stoneTarget;run(()=>E.equipStone(game,selected,item.id,slot))}if(item.kind==='stone'&&t.dataset.stoneRemoveTarget!==undefined&&item.originSlot!==undefined){run(()=>E.equipStone(game,item.originMonster||selected,null,+item.originSlot));}if(item.kind==='monster'&&t.dataset.teamSlot!==undefined){run(()=>{const index=+t.dataset.teamSlot,current=game.team.indexOf(item.id);if(current>=0){[game.team[current],game.team[index]]=[game.team[index],game.team[current]];game.team=game.team.filter(Boolean)}else{game.team[index]=item.id;game.team=game.team.filter(Boolean)}selected=item.id;return{ok:true,message:'队伍编成已更新'}})}if(item.kind==='monster'&&t.dataset.teamRemoveTarget!==undefined&&game.team.includes(item.id)){selected=item.id;run(()=>E.toggleTeam(game,item.id));}if(item.kind==='food'&&t.dataset.foodTarget!==undefined&&!game.cooking){const p=E.POTS.find(p=>p.id===pot),next=[...food],index=Math.min(+t.dataset.foodTarget,food.length);next[index]=item.id;const used=next.filter(id=>id===item.id).length*p.cost;if(game.inventory[item.id]>=used){food=next;render()}else notify('食材数量不足')}});document.addEventListener('dragend',()=>dragged=null);



document.addEventListener('native-font-ready',()=>paintNativeLabels());

let sceneDrag=null;const dragSurface=$('#game');
dragSurface.addEventListener('pointerdown',e=>{if(!['camp','map'].includes(view)||!$('#overlay').hidden||e.button!==0||e.target.closest('button,a,input,textarea,select,[role="dialog"]'))return;sceneDrag={id:e.pointerId,view,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,active:false};dragSurface.setPointerCapture(e.pointerId)});
dragSurface.addEventListener('pointermove',e=>{if(!sceneDrag||sceneDrag.id!==e.pointerId)return;if(sceneDrag.view!==view||!$('#overlay').hidden){sceneDrag=null;return;}if(!sceneDrag.active&&Math.hypot(e.clientX-sceneDrag.startX,e.clientY-sceneDrag.startY)<6)return;const scale=dragSurface.getBoundingClientRect().width/1280,pan=view==='camp'?panOriginalCamp:panOriginalIsland;pan((e.clientX-sceneDrag.x)/scale,(e.clientY-sceneDrag.y)/scale);sceneDrag.active=true;sceneDrag.x=e.clientX;sceneDrag.y=e.clientY;e.preventDefault();});
const endSceneDrag=e=>{if(sceneDrag?.id===e.pointerId){sceneDrag=null;if(dragSurface.hasPointerCapture(e.pointerId))dragSurface.releasePointerCapture(e.pointerId);}};
dragSurface.addEventListener('pointerup',endSceneDrag);dragSurface.addEventListener('pointercancel',endSceneDrag);dragSurface.addEventListener('lostpointercapture',()=>sceneDrag=null);



function canRecoverBattle(){return !!battle&&E.battleRecoveryEnabled(game,battle,E.battleRetireUnlocked(game))}
function showBattlePause(){if(!battle)return;$('#overlay').hidden=false;$('#overlay').innerHTML=nativeBattlePauseUI({tickets:ticketLabel(game),cost:E.battleRecoveryCost(battle),collectEnabled:canRecoverBattle(),failed:battle.status!=='fighting',itemsHTML:nativeBattlePauseItems({drops:battle.drops,ingredients:E.INGREDIENTS,foodIcon,gem,moveStoneIcon:s=>originalSprite('UI_Pstone_skill_'+({whack:'continue',broad:'extend',scatter:'nway',sharing:'addteambuff',stay:'buffprobup',wait:'charge'}[s.kind]))})});paint()}
function showBattleDecision(collect){$('#overlay').innerHTML=nativeBattleConfirmation({collect});paint()}
function finishBattleDecision(collect){if(!battle||battle.rewardClaimed)return;if(battle.status==='fighting'){battle.status='retreated';battle.paused=false;ended=true;}settleBattleResult(collect)}
function settleBattleResult(collect){lastReward=E.claimBattle(game,battle,{collectFailedDrops:collect});if(lastReward?.ok===false){if(lastReward.reason==='save-failed'){battle.pendingCollectDecision=collect;showDialog(`<h2>奖励尚未保存</h2><p>本地保存失败，奖励和进度尚未提交。请检查浏览器存储空间后重试，暂时不要关闭页面。</p><div class="dialog-actions"><button data-action="retry-battle-save">重试保存奖励</button></div>`);}else showBattlePause();return}failureDialogAt=null;save();syncMusic();showStageClear()}






function autoSetDetailStones(){run(()=>{const m=mon(selected),plan=originalAutoGamePlan({game,monster:m,species:sp(m.speciesId),unlockedCount:E.unlockedSlots(m),isSlotUnlocked:E.isSlotUnlocked,activeBingoCount:E.activeBingos});for(const a of plan.assignments)E.equipStone(game,selected,a.storageID,a.slotIndex);return{ok:true,message:'自动设置完成'}});}
function showDetailRecycle(){detailUIState={...detailUIState,recycleMode:true,recycleSelection:[],selectedStone:'',profile:false};render();}
function confirmDetailRecycle(ids){if(!detailUIState.recycleMode||!ids.length)return;$('#overlay').hidden=false;$('#overlay').innerHTML=nativeMonsterRecycleConfirmation();paint();}
document.addEventListener('click',e=>{if(!e.target.closest('[data-action="detail-recycle-confirm"]'))return;const ids=[...(detailUIState.recycleSelection||[])];closeDialog();const r=run(()=>E.recycleStones(game,ids));if(!r?.ok)return;detailUIState={...detailUIState,recycleMode:false,recycleSelection:[],page:0};render();$('#overlay').hidden=false;$('#overlay').innerHTML=nativeMonsterRecycleReward({items:originalMonsterRecycleRewardItems(r.ingredients,E.INGREDIENTS),foodIcon});paint();});
