import {CLIENT_CAMP_SOURCE as S} from './client-camp-source.js';
import {originalSprite} from './native-ui.js';
const base='Canvas_Common_UI/common_group/',scale=2/3;
const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const node=p=>S.nodes.find(n=>n.path===p);
const rect=n=>`left:${n.bounds[0]*scale}px;top:${n.bounds[1]*scale}px;width:${n.bounds[2]*scale}px;height:${n.bounds[3]*scale}px;`;
function art(p){const n=node(base+p);return n?n.images.map(im=>`<span class="camp-source-art" style="${rect(n)}${im.imageType===1?`border:solid transparent;border-width:${im.slices.map(v=>v*scale+'px').join(' ')};border-image:url('${im.src}') ${im.slices.join(' ')} fill stretch;`:`background:url('${im.src}') center/100% 100% no-repeat;`}"></span>`).join(''):'';}
function button(p,attrs,label,content=''){return `<button class="camp-source-hit" style="${rect(node(base+p))}" ${attrs} aria-label="${escape(label)}">${content}</button>`;}
function sourceLabel(p,value){const n=node(base+p);return n?`<span class="camp-source-text" style="${rect(n)}font-size:${(n.texts?.[0]?.fontSize||25)*scale}px">${escape(value)}</span>`:'';}
export function nativeCampBottom({game,species,pokemonIcon,teamPower}){
 let h='<div class="native-camp-bottom">';
 for(const p of ['button_option_window/button_menu_window','button_pokemon_window/button_team/button_pokemon_window','button_base_window/button_base_window'])h+=art(p);
 for(const [p,view,label]of [['button_menu','options','选项'],['button_record','quests','任务'],['button_zukan','dex','图鉴']]){const a='button_option_window/'+p+'/allround_button';h+=art(a)+art(a+'/icon')+button(a,`data-view="${view}"`,label)+sourceLabel(a+'/Text',label);}
 const team='button_pokemon_window/button_team/';h+=art(team+'button_menu/allround_button')+art(team+'button_menu/allround_button/icon')+button(team+'button_menu/allround_button','data-view="team"','队伍编成')+sourceLabel(team+'button_menu/allround_button/Text','队伍编成');
 for(let i=0;i<3;i++){const p=team+'button_pokemon'+(i+1)+'/allround_button',m=game.monsters.find(m=>m.uid===game.team[i]);h+=art(p)+art(p+'/monster_waku')+button(p,m?`data-monster="${m.uid}"`:'data-view="team"',m?species(m.speciesId).name:'添加队员',m?pokemonIcon(species(m.speciesId)):'＋')+sourceLabel(p+'/Text',m?species(m.speciesId).name:'');}
 h+=art(team+'team_power/window')+art(team+'team_power/window2')+art(team+'team_power/text_window')+art(team+'team_power/image')+sourceLabel(team+'team_power/text','TEAM POWER')+sourceLabel(team+'team_power/counter',teamPower(game).toLocaleString());
 const expedition='button_base_window/button_camp_worldmap/allround_button';h+=art(expedition)+art(expedition+'/base_camp')+button(expedition,'data-view="map"','出发探险')+sourceLabel(expedition+'/Text','出发探险');
 return h+'</div>';
}
function potArt(path,cls,style=''){const n=node('Canvas_pot/'+path);return n?.images.map(im=>`<span class="camp-source-art ${cls}" style="${style}${im.imageType===1?`border:solid transparent;border-width:${im.slices.map(v=>v*scale+'px').join(' ')};border-image:url('${im.src}') ${im.slices.join(' ')} fill stretch;`:`background:url('${im.src}') center/100% 100% no-repeat;`}"></span>`).join('')||'';}
export function nativeCampPots({game,count,cookingAtStation}){return Array.from({length:Math.min(4,count)},(_,i)=>{const c=cookingAtStation(game,i),total=Math.max(1,c?.total||c?.remaining||1),done=Math.max(0,total-(c?.remaining||0));let marker='';if(c?.ready)marker=originalSprite('BC_feelicon_cookfix');else if(c)marker=potArt('guage/BC_pot_guage_window','pot-bubble')+potArt('guage/BC_pot_guage_window/sankaku_L','pot-tail left')+potArt('guage/BC_pot_guage_window/sankaku_R','pot-tail right')+potArt('guage/Slider/Background','pot-gauge-bg')+`<span class="pot-gauge-fill" style="height:${done/total*53.333}px"></span>`+potArt('guage/waku','pot-bubble-frame')+`<span class="pot-count numerator">${done}</span><span class="pot-count denominator">${total}</span><span class="pot-count-slash"></span>`;return `<div class="camp-pot-ui" data-camp-pot="${i}" hidden><button class="pot-hotspot" data-camp-cook="${i}" aria-label="${i?'打开料理锅 '+(i+1):'打开料理锅'}"></button><button class="pot-marker ${c?.ready?'is-ready':c?'is-cooking':'is-empty'}" data-camp-cook="${i}" aria-label="${c?.ready?'领取料理完成的伙伴':c?`料理进度 ${done}/${total}`:'打开料理锅'}${i?' '+(i+1):''}">${marker}</button></div>`;}).join('');}
export function campDecorationDialog({game,decoration,placements}){const compatible=S.placements.filter(p=>p.category===S.goods.find(g=>g.id===decoration.sourceId)?.category);return `<h2>${escape(decoration.name)} · 摆放</h2><p>选择营地中的装饰位置，或旋转、收起当前装饰。</p><div class="camp-placement-grid">${compatible.map(p=>`<button data-camp-place="${decoration.id}" data-camp-slot="${p.id}" aria-pressed="${placements[decoration.id]?.slot===p.id}">位置 ${p.id+1}</button>`).join('')}</div><div class="dialog-actions"><button data-camp-rotate="${decoration.id}">旋转</button><button data-place="${decoration.id}">收起</button><button data-action="close">返回</button></div>`;}
export function campDecorationPlacements(game,decorations){const result={},used=new Set();for(const id of game.placedDecorations||[]){const d=decorations.find(d=>d.id===id),good=S.goods.find(g=>g.id===d?.sourceId);if(!good)continue;const available=S.placements.filter(p=>p.category===good.category),saved=game.campPlacements?.[id],p=available.find(p=>p.id===saved?.slot&&!used.has(p.id))||available.find(p=>!used.has(p.id));if(p){used.add(p.id);result[id]={slot:p.id,turn:saved?.turn||0};}}return result;}

function editorSkin(path){const im=node('Canvas_goods_Menu/'+path)?.images[0];return im?`border:solid transparent;border-width:${im.slices.map(v=>v*scale+'px').join(' ')};border-image:url('${im.src}') ${im.slices.join(' ')} fill stretch;background:transparent;`:'';}
export function nativeCampGoodsEditor({game,decorations,selected=''}){const d=decorations.find(d=>d.id===selected),placements=campDecorationPlacements(game,decorations),category=S.goods.find(g=>g.id===d?.sourceId)?.category;
 return `<section class="camp-goods-editor" aria-label="营地装饰编辑"><div class="camp-goods-panel" style="${editorSkin('goods_window/general_window/background')}"><h2>装饰</h2><div class="camp-goods-list">${decorations.filter(d=>game.decorations.includes(d.id)).map(d=>`<button data-camp-decoration="${d.id}" style="${editorSkin('goods_window/general_window/Mask/ScrollRect/product/button')}" aria-pressed="${d.id===selected}">${originalSprite(d.sprite||d.iconPath)}<span>${escape(d.name)}</span>${placements[d.id]?originalSprite('BaseCamp_checkmark','camp-goods-check'):''}</button>`).join('')||'<p>尚未获得装饰</p>'}</div><button class="camp-goods-shop" data-view="decorations" data-action="close">装饰商店</button></div>${d?S.placements.filter(p=>p.category===category).map(p=>`<button class="camp-goods-slot" data-camp-place="${d.id}" data-camp-slot="${p.id}" data-slot-world="${p.position.join(',')}" aria-label="摆放至位置 ${p.id+1}" aria-pressed="${placements[d.id]?.slot===p.id}">＋</button>`).join(''):''}${d?`<div class="camp-goods-controls"><strong>${escape(d.name)}</strong><button data-camp-rotate="${d.id}" ${placements[d.id]?'':'disabled'} aria-label="旋转">${originalSprite('BaseCamp_rotate_button')}旋转</button><button data-camp-store="${d.id}" ${placements[d.id]?'':'disabled'} aria-label="收起">${originalSprite('BaseCamp_delete_button')}收起</button></div>`:''}<button class="camp-goods-exit" data-action="close" aria-label="退出装饰编辑">${originalSprite('button_allround_exit')}</button></section>`;
}

export function campCanPlace(decoration,slot){const category=S.goods.find(g=>g.id===decoration?.sourceId)?.category;return S.placements.some(p=>p.id===slot&&p.category===category);}
export function campRotationStep(decoration){return S.goods.find(g=>g.id===decoration?.sourceId)?.category===2?1:2;}
